### ISSUE TITLE
Conflict with angular-mocks

### ISSUE THREAD

**Issue by mikeborozdin** [philbooth/check-types.js#23]
Hi,

We really like ```check-types.js```. However, we've run into problems when unit testing an Angular.JS application. There is a conflict with ```angular-mocks```.

```check-types.js``` attempts to detect an environment in order to load itself. While doing that it checks whether ```module``` is ```defined```. If so, it assumes it's in the Node.JS environment and attaches itself to ```module.exports```. 

The problem arises when using ```angular-mock```. It defines ```window.module``` which confuses ```check-types.js``` if ```angular-mocks``` is loaded before ```check-types``` in ```karma```, e.g.:

```
files: [
  'app/bower_components/angular/angular.js',
  'app/bower_components/angular-mocks/angular-mocks.js',
  'app/bower_components/check-types/src/check-types.min.js',
]
```

While we can solve the problem by placing ```check-types.js``` above ```angular-mocks```, it is extremely brittle, as we have to depend on script loading mechanism of ```karma```, which we cannot control.

Also, since we've got ```check-types``` as a Bower dependency, does it make sense to check for Node.JS environment? Can't we just assume that we are in a browser and simply attach it to the ```window``` object?

**Comment by philbooth** [comment]
Closing this due to lack of feedback. Feel free to re-open if it is still a problem though; any guidance on the correct fix would also be useful in that case. :)
