### ISSUE TITLE
Implement `within` predicate

### ISSUE THREAD

**Issue by philbooth** [philbooth/check-types.js#34]

**Comment by yangchenyun** [comment]
Why this is closed? I would vote for all: `greaterorequal`, `lessorequal`, `within`.
If I want to have integer in range [0, 20], it is hard to write assertion with current methods now.

**Comment by philbooth** [comment]
I'd argue that its covered by `between`. Likewise `greaterOrEqual` and `lessOrEqual` are covered by `greater`and `less` respectively.

The requirement to add or subtract one from the target value seems reasonable and not worth the burden of increasing the library/interface size by three functions, imho.

**Comment by yangchenyun** [comment]
The add/subtract one approach is not enough when the float number kicks in. For example I want to have valid [0, 20] (inclusive range), what I am doing right now is  `check.between(0-1e-20, 20+1e-20)`.

`>`, `>=` operators are almost widely provided by all main stream languages, so I will think of them as necessities.

**Comment by philbooth** [comment]
Good point. I failed to consider floats completely, sorry.

Let's add them. I'm not sure how I feel about `within` as a predicate name given that `between` also exists. They seem ambiguous and conflicty. I'm also aware that I've made naming errors before in this lib.

What do you think the best name for that predicate would be?

**Comment by yangchenyun** [comment]
As `between` is an established API name, hard to change it; `within` seems reasonable to me, or `inrange`?

**Comment by philbooth** [comment]
Just published version 3.3.0 with the predicates `greaterOrEqual`, `lessOrEqual` and `inRange`. Let me know if there's any problems, thanks. :)

**Comment by yangchenyun** [comment]
Awesome! Thank!
