### ISSUE TITLE
check.map fails if number of properties do not match

### ISSUE THREAD

**Issue by graetzer** [philbooth/check-types.js#36]
This line causes check.map to fails if the predicate object contains more properties than the data object.
https://github.com/philbooth/check-types.js/blob/master/src/check-types.js#L383
Doesn't this break the usage of the `check.maybe.xxx(...)` modifier?

    function map (data, predicates) {
       var result = {}, keys;
       // ...
       keys = Object.keys(predicates);
       assert.length(Object.keys(data), keys.length);
       // ...

**Comment by philbooth** [comment]
Good point, thanks for raising it. I plan to release a new version next weekend and will make sure this gets addressed at the same time.
