### ISSUE TITLE
Implement arrayLike predicate

### ISSUE THREAD

**Issue by philbooth** [philbooth/check-types.js#39]
There should be a predicate for checking whether something is an array-like object. As well as being exposed as a predicate in its own right, it should also be utilised by `map`, `apply` and `of` so that they work sanely with array-like objects.

**Comment by MareoRaft** [comment]
I would recommend

    check.iterable()

for the name of this predicate.  I learned about the term `iterable` in a pluralsight.com course I am learning from called Javascript Fundamentals for ECMAScript 6.  According to the professor, who seems very trustworthy, `iterable`s and iterators are being standardized in ES6.  So by choosing this name now, you will remain consistent with programmers as they switch over to ES6.

**Comment by philbooth** [comment]
Yep, good shout. I'll definitely do that.

**Comment by philbooth** [comment]
Fyi, this is now implemented. I'll release as soon as issues #28 and #41 are resolved.

**Comment by philbooth** [comment]
Published as 3.2.0.

**Comment by MareoRaft** [comment]
check.iterable() is working for me.
