### ISSUE TITLE
How to find out which assertion is causing an uncaught error?

### ISSUE THREAD

**Issue by philbooth** [philbooth/check-types.js#51]
Asked [elsewhere](https://github.com/philbooth/check-types.js/issues/44#issuecomment-124308895):

>  Excuse me if I am posting this in the wrong place. I am getting the message "Uncaught Error: Invalid object". I wish it would tell me which check.assert in my code caused the failure (line number), as well as the actual type and value of the variable it was checking. I don't know what is and is not possible.

@MareoRaft

Are you running in node.js? If so you can add a listener for the `uncaughtException` event like so:

```js
process.on('uncaughtException', function (error) {
    console.log(error.stack);
});
```

Alternatively, if you're in a browser you can try doing something similar using [`window.onerror`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror).

**Comment by MareoRaft** [comment]
I am not using node.js.  My project is a website that loads a local check-types file via RequireJS.  Can you give an example of how I might use `window.onerror`?  That sounds very useful!  :)

**Comment by philbooth** [comment]
Depending on which browser you're in, you may find it easier to use the developer tools to break on unhandled errors so that you can also view the call stack at the time of the error:

* [Instructions for Firefox](https://developer.mozilla.org/cs/docs/Tools/Debugger#Debugger_settings).
* [Instructions for Chrome](https://developer.chrome.com/devtools/docs/javascript-debugging#pause-on-exceptions).

Alternatively, the `window.onerror` approach should look something like this:

```js
window.onerror = function(message, url, line, column) {
    console.log('Error from %s, line %d, column %d:\n%s', url, line, column, message);
};
```

**Comment by MareoRaft** [comment]
I started using Google Chrome for development now, which includes a dropdown on uncaught Exceptions with the stack trace.

**Comment by MareoRaft** [comment]
Just a note for anyone with a similar issue.  Chrome Canary seems to have stack traces when regular Chrome does not.
