### ISSUE TITLE
check.all() behaves like check.any()

### ISSUE THREAD

**Issue by Dmitri-Sintsov** [philbooth/check-types.js#53]
data = {'sender_id': 1, 'ts': '1234.56', 'recipient_ids': [1,2,3,4,5,6]}

    App.check.map(data, {'sender_id': App.check.integer, 'ts': App.check.string, 'recipient_ids': App.check.array})
    Object {sender_id: true, ts: true, recipient_ids: true}

    App.check.all(data, {'sender_id': App.check.integer, 'ts': App.check.string, 'recipient_ids': App.check.array})
    true

    App.check.map(data, {'sender_id': App.check.integer, 'ts': App.check.string, 'recipient_ids': App.check.integer})
    Object {sender_id: true, ts: true, recipient_ids: false}

    App.check.all(data, {'sender_id': App.check.integer, 'ts': App.check.string, 'recipient_ids': App.check.integer})
    true

Google Chrome 45 console. check is loaded to App.check via require.js.

check-types is the latest version from this repository.

**Comment by philbooth** [comment]
Oh, whoops. Thanks for reporting this, I'll dig into it over the weekend.

**Comment by Dmitri-Sintsov** [comment]
Also I am unsure that

    App.check.all(null, {'sender_id': App.check.integer, 'ts': App.check.string, 'recipient_ids': App.check.integer})

should produce

    Uncaught Error: Invalid object(…)

It would be more logical to produce false.
Of course I can catch however the point of such assertions to minimize the amount of code.

**Comment by philbooth** [comment]
@Dmitri-Sintsov, I wasn't paying attention before, sorry. Actually your usage of `all` is wrong; it only expects one argument, which should be the result from `map` or `apply`. So instead your code should look something like this:

```js
var data = {
  sender_id: 1,
  ts: '1234.56',
  recipient_ids: [ 1, 2, 3, 4, 5, 6 ]
};

App.check.all(
  App.check.map(data, {
    sender_id: App.check.integer,
    ts: App.check.string,
    recipient_ids: App.check.array
  })
); // returns true

App.check.all(
  App.check.map(data, {
    sender_id: App.check.integer,
    ts: App.check.string,
    recipient_ids: App.check.integer
  })
); // returns false
```

I'll have a look at trying to improve the documentation so that this usage is clearer.
