### ISSUE TITLE
err instanceof Error

### ISSUE THREAD

**Issue by missinglink** [philbooth/check-types.js#54]
hey @philbooth I am trying to `check.error()` on a **FandangledError** object which *inherits* from `Error`, eg this: https://github.com/elastic/elasticsearch-js/blob/master/src/lib/errors.js

instead of `toString()` returning `'[object Error]'` it returns `'[object Object]'` however `err instanceof Error` returns `true`

thoughts?

**Comment by philbooth** [comment]
Hello mate. :)

Yep, I think the two tests should be `||`-combined. Feel free to PR, if not I'll do it over the weekend.

And as it's a breaking change, I'll also use the major version bump to make [certain other interface changes](https://github.com/philbooth/check-types.js/issues/45) that have been requested elsewhere.

**Comment by philbooth** [comment]
Fixed and published to npm as version 4.0.0.

**Comment by missinglink** [comment]
Thanks @philbooth I will be visiting London from the 23rd so I can buy you a :beer:!

**Comment by philbooth** [comment]
> I will be visiting London from the 23rd...

Noted in calendar.
