### ISSUE TITLE
[meta] "bump version" commits

### ISSUE THREAD

**Issue by MarkHerhold** [philbooth/check-types.js#57]
Hi @philbooth

Excellent work on this library. I absolutely love it. :heart_eyes: 

In the future, do you think it would be possible to include the version number in the commit history? Currently, it isn't exactly easy to figure out what version corresponds to what commit because you always have "bump version". It appears that you already use [`npm version`](https://docs.npmjs.com/cli/version) because you have everything tagged so nicely (thanks!), so perhaps you could include the version number in the commit with `%s` in the `npm version` command?  e.g. `npm version patch -m "Upgrade to %s for reasons"`

Thanks for the consideration.

**Comment by philbooth** [comment]
Noted, I'll make sure I do it in future releases.

However, you should also be aware that bumping the version is not always the last commit in a release, sometimes I forget to update the readme or do minification or whatever, so they come after. So the tagged commit might come some time after the version bump.

For that reason, I find it helpful to have an alias for `git log` that includes tag and branch information, so I can see exactly when a release got tagged and what the version number was. This is what it aliases to, sharing just in case it's of interest:

```sh
git log --graph --all --abbrev-commit --pretty=format:'%C(red)%d%x20%C(yellow)%h%x20%C(green)%an%x20%Creset%s'
```

**Comment by MarkHerhold** [comment]
`npm version` will create the tag for you along with bump the version and create the commit message with the version number in it. Then all you need to do is push with tags `git push --tags`. That may help depending on your release process.

Thanks for the `git log` trick! I just googled it and it seems that `git log --decorate` does some similar tricks. `git log --decorate --all --oneline --graph` is great for this too!

I'll close this after a day or two or you can whenever you like. Thanks again!

**Comment by philbooth** [comment]
Thanks, I'll leave this issue open until the next release, otherwise I'll forget about it.
