### ISSUE TITLE
emptyString feature request

### ISSUE THREAD

**Issue by MareoRaft** [philbooth/check-types.js#58]
Can we have an emptyString method?

This would return the negation of the nonEmptyString method.

Thanks!
-Mareo

**Comment by philbooth** [comment]
Yep, sounds reasonable enough. I've got a few changes lined up that I plan to make this weekend, I'll aim to do this at the same time.

**Comment by philbooth** [comment]
Forgot to say, this got implemented yesterday in version `5.0.0`.

**Comment by MareoRaft** [comment]
sweet
