### ISSUE TITLE
Is "and" possible?

### ISSUE THREAD

**Issue by ibc** [philbooth/check-types.js#60]
I want to check that a given variable holds a positive integer value. No direct API for that in this lib, so I wonder whether I could use something like:

```js
check.integer(x).and.positive(x);
```

Is there something to achieve this?

**Comment by philbooth** [comment]
At the moment you need to `&&` predicates together yourself, but I'll look into adding something soon. It will probably need to lean on the same chaining solution that is required for #56, so hopefully I can sort them out together.

Also, note that if you have a lot of predicates that you want to combine in this way, you might find it easier to use `.all()` and `.map()` / `.apply()`.

**Comment by ibc** [comment]
Clear. Thanks a lot.

**Comment by philbooth** [comment]
I'll keep this issue open though. Otherwise, I'll forget all about it. :grin:

**Comment by ibc** [comment]
Of course, sorry :)

**Comment by philbooth** [comment]
Fwiw, I've decided not to implement this. There is an `all` batch function that can be used to model complex and-relationships, otherwise I think it best expressed in JS.

For the same reason, I've removed the `either` modifier. As of version `6.0.0`, there is no `check.either`.

**Comment by ibc** [comment]
Makes sense. Thanks.
