### ISSUE TITLE
nonEmpty* predicates for objects and arrays

### ISSUE THREAD

**Issue by Gipphe** [philbooth/check-types.js#72]
Would be nice with proper `nonEmptyObject` and `nonEmptyArray` predicates, instead of having to use something along the lines of 
```javascript
check.object(obj) && check.not.emptyObject(obj)
```

Willing to do a PR if this is sensible.

**Comment by philbooth** [comment]
> Would be nice with proper `nonEmptyObject` and `nonEmptyArray` predicates...

👍

> Willing to do a PR if this is sensible.

Yep, bring it on!
