### ISSUE TITLE
Possible 'maybe' issue

### ISSUE THREAD

**Issue by dkhuntrods** [philbooth/check-types.js#76]
Hello again, and apologies for posting again so soon.
I've got another potential issue that I suspect is related to #75.
Essentially, adding `maybe` to an `assert` that checks an invalid string value seems to grab that string value instead. I've created a test here:

https://runkit.com/dkhuntrods/58889646a141cf0016208c68

Thanks again.

**Comment by philbooth** [comment]
No probs, thanks for raising the issues!

Looks like there are some holes in my test coverage that need filling. 😄

**Comment by dkhuntrods** [comment]
@philbooth Great, thanks! Let me know if I can help at all :)
(FTR, seems to be the same thing with `not`, if that helps track it down)

**Comment by philbooth** [comment]
Apologies again for this, it should be fixed in version `7.1.3`, published just now. Let me know if you get any problems!

**Comment by dkhuntrods** [comment]
Amazing, thanks for fixing this so quickly.
All seems to be well!
