### ISSUE TITLE
Wrap in process.env.NODE_ENV

### ISSUE THREAD

**Issue by milesj** [philbooth/check-types.js#80]
I'm currently using this library to validate configuration objects/options while in development. To accomplish this, code is wrapped in `if (process.env.NODE_ENV !== 'production') {` blocks, so that they're removed during minification and not included in the final bundle. This works.

However, since this library is imported in the module scope, the entirety of the library is included in the bundle, when it's not really necessary. A version of this library wrapped in prod/dev checks would be rather helpful.

**Comment by philbooth** [comment]
Hey @milesj, thanks for opening this!

As this lib also targets browser environments, at the moment I'm not minded to do it in the lib itself. However it seems like it should be straightforward to have your own local wrapper which does the `NODE_ENV` checks, and then import that module instead? Would that work for you or is there some reason it needs to be done inside `check-types`?

**Comment by milesj** [comment]
Yeah, that's pretty much what I've been planning to do (haven't had a chance yet). I'll report back and see how it goes.

**Comment by milesj** [comment]
Got this working with a different approach. Will close for now.
