### ISSUE TITLE
Add a check for promises

### ISSUE THREAD

**Issue by shane805** [philbooth/check-types.js#86]
I'd like to propose adding a convenient way to check if something is a promise.

I think it would be as simple as checking if an object has a `then` property that is a function.

Here's a PR for the change:
https://github.com/philbooth/check-types.js/pull/85

**Comment by philbooth** [comment]
Hey @shane805, thanks for the PR!

Although the code looks great, I think I'm -1 to the proposal. Generally I've tried to avoid object-specific predicates like that to try and keep the library size as small as possible.

You can achieve the same result by calling `check.instance(foo, Promise)` or `check.instanceStrict(foo, Promise)`. Do either of those work for your use case?
```

**Comment by shane805** [comment]
Hey @philbooth 

No problem that makes total sense. Using `check.instance` will do the trick. 

+1 for keeping the library small!

Thanks for taking the time to look into this!
